Provide a Box to GMX matrix converter
victorusu/gromacs pull request #2
Opened 2019-11-22 19:48 UTC by victorusu

2019-11-24 01:47 UTC, ejjordan approved these changes

2019-11-25 11:28 UTC, sebkelle1 commented
lgtm

2019-11-25 11:31 UTC, sekelle requested changes
Change assignment to double loop

2019-11-25 11:31 UTC, sebkelle1 commented on src/gromacs/nblib/box.cpp
> +
Actually, this could be a double for-loop, using the DIM macro

2019-11-25 12:08 UTC, ejjordan commented
This is actually not the right implementation. In src/gromacs/math/matrix.h there is a definition of matrix in terms of mdspan called Matrix3x3 (and friends) that we should use instead of this. We should not use  any array functionality but instead use the data types in matrix.h directly.

2019-11-27 21:13 UTC, ejjordan reviewed
This is superseded by branch nblib_mdspan_box

2019-11-27 21:13 UTC, closed without merging