[RFC] Nblib nbnxn setup encapsulation
victorusu/gromacs pull request #35
Opened 2020-02-14 15:06 UTC by kanduri

I managed to separate the user facing client code from the underlying GMX code using a translation layer.

The `ForceCalculator` object would contain in it two other objects. One of them would be the `GmxForceCalculator` which would work with all GMX data structures internally and the other would be a builder (`NbvSetupUtil`) for this that would take in the data structures created by the user and fill the required GMX structures underneath.

I also attempted to separate the data created in the beginning of the simulation and the data transformed in each step. 

I am yet to upload tests. I am still writing tests and modifying code to make it more testable. In the process, I am splitting the functions a bit more so that I can limit their scope for better unit testing.

2020-02-17 13:56 UTC, kanduri commented
Some observations about the design:

- `GMXForceCalculator` knows nothing about the user level data structures and the simulation state. It is meant to evolve for the singular purpose of orchestrating internals of GROMACS.

- `NbvSetupUtil` (tentative naming, please suggest others) is the translation layer that holds a handle to the user level data structures and sets up the `GMXForceCalculator`

- Both of the above objects are structs with fully public interfaces and attributes. However, they are private members of `ForceCalculator`. User trying to script particle simulations cannot (and should not) be able to access it. However, we would be able to **test the functionality without using the client code**.

Looking brainstorm a bit on the tests we need to write and how we should invoke them.

2020-02-18 18:22 UTC, sekelle requested changes

2020-02-18 18:22 UTC, sekelle commented on src/gromacs/nblib/gmxsetup.cpp
> +
This is missing the most recent updates by Joe and me. Please merge the from nblib.

2020-02-18 18:22 UTC, sekelle commented on src/gromacs/nblib/gmxsetup.cpp
> +GmxForceCalculator::GmxForceCalculator(SimulationState system, const NBKernelOptions &options) : enerd_(1, 0), verletForces_({})
It's not so nice to copy the entire system just to access the box and the number of AtomTypes.
IMHO, neither the NbvSetupUtil, nor the GmxForceCalculator should have their own copy of the SimulationState. For now, I would say, we store a SimulationState in the ForceCalculator and pass on shared pointers to NbvSetupUtil and GmxForceCalculator.
We can then later change the ForceCalculator to also receive a shared pointer and make the user or mdrunner object own the SimulationState.

2020-02-18 18:22 UTC, sekelle commented on src/gromacs/nblib/gmxsetup.h
> +    gmx::PaddedHostVector<gmx::RVec> verletForces_;
I don't see the point of this member. The compute function returns by value, so the forces are first copied into the member, and then into the return value. This is worse compared to a function local object that's being returned by value in compute. The way to optimize this function would be to have compute take a reference and let the user supply the storage, but this we can address later.

2020-02-18 18:22 UTC, sekelle commented on src/gromacs/nblib/gmxsetup.cpp
> +    gmxForceCalculator_p->verletForces_.resizeWithPadding(nbat->numAtoms());
This reintroduces the no-zero-init bug we just fixed

2020-02-19 16:26 UTC, kanduri commented on src/gromacs/nblib/gmxsetup.cpp
> +GmxForceCalculator::GmxForceCalculator(SimulationState system, const NBKernelOptions &options) : enerd_(1, 0), verletForces_({})
Agreed. Turned it into a shared pointer for now.

2020-02-19 16:26 UTC, kanduri commented on src/gromacs/nblib/gmxsetup.cpp
> +
Done.

2020-02-19 16:27 UTC, kanduri commented on src/gromacs/nblib/gmxsetup.h
> +    gmx::PaddedHostVector<gmx::RVec> verletForces_;
Cool. Just returning a reference for now.

2020-02-19 16:46 UTC, kanduri commented on src/gromacs/nblib/gmxsetup.cpp
> +    gmxForceCalculator_p->verletForces_.resizeWithPadding(nbat->numAtoms());
Fixed

2020-02-25 15:22 UTC, closed without merging