fixed topology ctor and createExclusionList
victorusu/gromacs pull request #5
Opened 2019-11-25 16:48 UTC by sebkelle1

Change-Id: I5c32e3da03a9a03c8f141ad07609326680f69beb

2019-11-26 10:05 UTC, ejjordan requested changes
Sorry for not understanding and consequently misleading everyone on how the t_blocka structure works. Please have a look at the definition of t_blocka to make sure my comment below makes sense and is correct. At some point soon I hope to have a nice structure to replace t_blocka with. It will probably be two arrays or vectors but have the same basic structure of the current t_blocka. There is support for just having some nice free function in gromacs core that turn a std::vector<std::tuple<int, int>> into the cache efficient but c++ified t_blocka replacement structure (and back again if needed).

2019-11-26 10:05 UTC, ejjordan commented on src/gromacs/nblib/topology.cpp
> +            auto shiftedExclusions = exclusionBlockPerMolecule;
The name shiftedExclusions is not so nice since there are shifts in MD codes and in practice exclusions may be shifted (that is, wrapped around to an opposing box face) as well. I also don't understand why this rename (copy?) is necessary. Can't we just loop over exclusionBlocksPerMolecule?

2019-11-26 10:05 UTC, ejjordan commented on src/gromacs/nblib/topology.cpp
> +    snew(tBlockGlobal.a, numberOfExclusions + 1);
I was mistaken about the structure of t_blocka. It is actually one list with all the exclusions and one list with the indices of exclusion block start and ends:
blocks (.index): [0, endBlock1(==startBlock2 - 1), endBlock2(==startBlock3 - 1), ...]
exclusions (.a): [i, j, ..., IndexEndBlock1, IndexEndBlock1 + 1, k, l, ..., IndexEndBlock2, ...]
See src/topology/block.h for the definition.
For LJ particles index==a but in general index.size()==numAtoms + 1 and a.size()==numExclusions

2019-11-27 20:21 UTC, ejjordan approved these changes
With the (very small) change I made I think this is ready.

2019-11-28 08:42 UTC, sebkelle1 commented
I changed shiftedExclusions to offsetExclusions

2019-11-28 09:15 UTC, kanduri approved these changes
LGTM

2019-11-28 09:23 UTC, merged